### ISSUE TITLE
安装完mp-sentry之后，请求接口会把错

### ISSUE THREAD

**Issue by rosa5500** [imingyu/mp-sentry#2]
![WX20240605-154537@2x](https://github.com/imingyu/mp-sentry/assets/42903030/6b56d7ce-22de-47af-a7d3-830952f92e52)
想问下，有什么思考方向吗？（小程序原生，wx.request）
---------
我debugger了一下，只要访问到wx.getNetworkType().then()这里就不会向下走了。wx.getNetworkType()返回了undefined（正常应该是一个promise）
---------
另外，好像是weconsole团队的开发大佬，我安装weconsole也有上述同样的问题。
--------
感谢。

**Comment by rosa5500** [comment]
> ## ![WX20240605-154537@2x](https://private-user-images.githubusercontent.com/42903030/336740280-6b56d7ce-22de-47af-a7d3-830952f92e52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NzQ0OTEsIm5iZiI6MTcxNzU3NDE5MSwicGF0aCI6Ii80MjkwMzAzMC8zMzY3NDAyODAtNmI1NmQ3Y2UtMjJkZS00N2FmLWE3ZDMtODMwOTUyZjkyZTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA3NTYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZGNlNzJjYjUwNWU4YWJmMGE1MzNiZmRlZmViMGU4YmUyNGZjNDlkYTFjZTE3MGJlNTY0N2RkODI5OTU4OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c9UFpBfaIhlLKvR9z6NAy_seES4ilup0mKc1J0dB9J0)
> 想问下，有什么思考方向吗？（小程序原生，wx.request）
> ## 我debugger了一下，只要访问到wx.getNetworkType().then()这里就不会向下走了。wx.getNetworkType()返回了undefined（正常应该是一个promise）
> ## 另外，好像是weconsole团队的开发大佬，我安装weconsole也有上述同样的问题。
> 感谢。

图片加载失败：
TypeError: [captureOfMixin]Cannot read property 'code' of undefined
    at _callee$ (index.js? [sm]:33)
    at s (regeneratorRuntime.js:1)
    at Generator.<anonymous> (regeneratorRuntime.js:1)
    at Generator.next (regeneratorRuntime.js:1)
    at asyncGeneratorStep (asyncToGenerator.js:1)
    at c (asyncToGenerator.js:1)(env: macOS,mp,1.06.2310080; lib: 3.2.5)

**Comment by imingyu** [comment]
正常情况下wx.getNetworkType()执行后不会返回Promise啊，是不是你项目里重写过wx变量，把方法的返回值改成Promise了？

**Comment by rosa5500** [comment]
> 正常情况下wx.getNetworkType()执行后不会返回Promise啊，是不是你项目里重写过wx变量，把方法的返回值改成Promise了？

<img width="491" alt="image" src="https://github.com/imingyu/mp-sentry/assets/42903030/0ae4fbde-26cb-4144-80b5-0a29e7a31599">
<img width="838" alt="image" src="https://github.com/imingyu/mp-sentry/assets/42903030/a1ba22fc-035e-4fd8-9c58-a7f929c7947d">

感谢！应该是时间太久了，小程序更新了。支持两种方式。

**Comment by rosa5500** [comment]
> 正常情况下wx.getNetworkType()执行后不会返回Promise啊，是不是你项目里重写过wx变量，把方法的返回值改成Promise了？

感谢感谢！查看了getNetWorkType的文档，应该是时间太久了，小程序更新了。
至少找到原因了~~等待大佬兼容

`
wx.getNetworkType(Object object)
以 [Promise 风格](https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/api.html#%E5%BC%82%E6%AD%A5-API-%E8%BF%94%E5%9B%9E-Promise) 调用：支持

小程序插件：支持，需要小程序基础库版本不低于 [1.9.6](https://developers.weixin.qq.com/miniprogram/dev/framework/compatibility.html)
`

`
异步 API 返回 Promise
基础库 [2.10.2](https://developers.weixin.qq.com/miniprogram/dev/framework/compatibility.html) 版本起，异步 API 支持 callback & promise 两种调用方式。当接口参数 Object 对象中不包含 success/fail/complete 时将默认返回 promise，否则仍按回调方式执行，无返回值。

// callback 形式调用
wx.chooseImage({
  success(res) {
    console.log('res:', res)
  }
})

// promise 形式调用
wx.chooseImage().then(res => console.log('res: ', res))

`
https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/api.html#API
